#!/bin/bash

set -e

. /usr/share/debconf/confmodule

WEBAPPS=/var/lib/tomcat6/webapps

function unpack_war() {
    cp /usr/share/opengeo-geoserver/geoserver.war $WEBAPPS
    unzip  -o /var/lib/tomcat6/webapps/geoserver.war  -d $WEBAPPS/geoserver  > /dev/null 2>&1
    chown tomcat6. /usr/share/opengeo-geoserver/*.war
}

case "$1" in
  install)
    # unpack the war
    unpack_war
    ;;

  upgrade)
    # don't totally blow away the old exploded war, save the web.xml since it
    # has configuration in it
    if [ -e $WEBAPPS/geoserver ]; then
      # clear out the old lib dir
      rm -f $WEBAPPS/geoserver/WEB-INF/lib/*

      # back up the old web.xml
      TMP=/tmp/opengeo-geoserver
      mkdir $TMP; cp $WEBAPPS/geoserver/WEB-INF/web.xml; 

      # unpack the new war
      unpack_war

      # restore old web.xml
      cp $TMP/web.xml $WEBAPPS/geoserver/WEB-INF
    else
      # not there, treat as regular install
      unpack_war
    fi
    
    ;;

  abort-upgrade)
    ;;

  *)
    echo "preinst called with unknown argument '$1'" >&2
    exit 1
    ;;

esac

#DEBHELPER#
