


clean: 
	rm -rf debian/geoserver


install: 
	mkdir -p debian/geoserver/usr/local/geoserver/
	cp -r bin/ debian/geoserver/usr/local/geoserver/
	cp -r data_dir/ debian/geoserver/usr/local/geoserver/
	cp -r etc/  debian/geoserver/usr/local/geoserver/ 
	cp -r lib/ debian/geoserver/usr/local/geoserver/ 
	cp -r logs/ debian/geoserver/usr/local/geoserver/ 
	cp -r resources/ debian/geoserver/usr/local/geoserver/ 
	cp -r webapps/ debian/geoserver/usr/local/geoserver
	cp start.jar debian/geoserver/usr/local/geoserver