#!/bin/bash

SVN_REPO=http://svn.opengeo.org/suite
BUILDS=http://suite.opengeo.org/builds

if [ "$REPO_PATH" == "" ]; then
  REPO_PATH=trunk
fi
if [ "$REV" == "" ]; then
  REV=latest
fi

BRANCH=${REPO_PATH//\//-}

PACKAGE=`echo $0 | sed 's#^.*build_##g' | sed 's#\.sh##g'`
RPM_BUILD_ROOT=`pwd`/rpmbuild
PKG_SOURCE_DIR=${RPM_BUILD_ROOT}/SOURCES/$PACKAGE

# build_info <package>
function build_info() {
  local pkg=$1
  if [ "$pkg" != "" ]; then
     name=$PACKAGE
  fi
  echo "Building $pkg from $REPO_PATH at revision $REV"
}

# checkrc <code> <message>
function checkrc() {
  if [ "$1" != 0 ]; then
    echo "$2 failed returning $1"
    exit 1
  fi
}

# get_file <url> [overwrite]
function get_file() {
  local url=$1
  local file=`echo $url | sed 's#http://##g' | xargs basename`

  if [ ! -d files ]; then
     mkdir files
     checkrc $? "mkdir files"
  fi

  if [ "$2" != "" ] ||  [ ! -e files/$file ]; then
     wget $url
     checkrc $? "downloading $url"

     mv $file files
     checkrc $? "mv $file files"
  fi
}

# get_svn <repo_path> <dir> <path>
function get_svn() {
  local repo_path=$1
  local dir=$2
  local path=$3

  if [ ! -d svn ]; then
    mkdir svn
    checkrc $? "mkdir svn"
  fi

  if [ ! -d svn/$repo_path ]; then
    mkdir svn/$repo_path
    checkrc $? "mkdir svn/$repo_path"
  fi

  pushd svn/$repo_path
  if [ -d $dir ]; then
    svn up $dir
  else
    svn co $SVN_REPO/$repo_path/$path $dir
  fi
  checkrc $? "svn update"
  popd
}

# clean_src
function clean_src() {
  rm -rf ${PKG_SOURCE_DIR}
}

# build_rpm
function build_rpm() {
  
  pushd ${RPM_BUILD_ROOT}/SPECS
  rpmbuild --buildroot ${RPM_BUILD_ROOT}/BUILDROOT -bb $PACKAGE.spec
  rc=$?
  popd
  checkrc $rc "rpmbuild"

  if [ ! -d build ]; then
    mkdir build
    checkrc $? "mkdir build"
  fi
  
  mv ${RPM_BUILD_ROOT}/$PACKAGE-*.rpm build
  checkrc $? "mv rpm"

}
