#!/bin/bash

function usage() {
  echo "Usage: opengeo-suite <start|stop>"
}

if [ "$1" == "" ]; then
  usage
  exit
fi

pushd "`dirname "$0"`" > /dev/null
 
if [ ! -e "`pwd`/og-jetty.jar" ]; then
  echo "Could not find og-jetty.jar"
  exit -1
fi

_RUNJAVA=""
if [ -e "`pwd`/jre" ]; then
  _RUNJAVA="`pwd`/jre/bin/java"
else
  if [ "$JAVA_HOME" != "" ] && [ -e $JAVA_HOME/bin/java ]; then
    _RUNJAVA=$JAVA_HOME/bin/java
  else
    which java > /dev/null
    if [ "$?" == "1" ]; then
      echo "JAVA_HOME is not defined, and java is not on the current PATH"
      exit
    fi
    _RUNJAVA=`which java`
  fi
fi

CLASSPATH=og-jetty.jar:jetty-start.jar:lib/ini4j-0.5.1.jar:lib/log4j-1.2.14.jar:lib/commons-logging-1.0.jar:lib/slf4j-jcl-1.0.1.jar
OPTS="-Dslf4j=false -cp $CLASSPATH"

case "$1" in

  start)
    #GDD=$GEOSERVER_DATA_DIR
    #if [ "$GDD" == "" ]; then
    #  GDD=`pwd`/data_dir
    #fi

    exec "$_RUNJAVA" $OPTS org.opengeo.jetty.Start
    ;;

  stop)
    exec "$_RUNJAVA" $OPTS org.opengeo.jetty.Start --stop
    ;;
   
  *)
    usage
esac

popd > /dev/null
